### PR TITLE
replication: update LastSyncTime if its not nill

### PR DESCRIPTION
**Pull request by Madhu-1**
LastSyncTime can be optional and nil also, there is no strict check for it, and if we dont have this check the [default UNIX time](https://go.dev/play/p/81CmSxr-r8S) will get added to the CR, which doesn't make sense. If the time is not present keep the last known LastSyncTime itself.

Depends-On: csi-addons/spec#47

### CODE REVIEW

**Review by ShyamsundarR — COMMENTED** [review]
This works to not update last known lastSyncTime in cases where the call does not return a value, or hold it at epoch till it does.

NOTE: As I have not cross-checked other areas of code not approving as such.

**Review by yati1998 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@nixpanic PTAL

**Review by ShyamsundarR — COMMENTED** [review]
LGTM!

**Review by nixpanic — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by yati1998 — APPROVED** [review]

**Pull request merged**
