### PR TITLE
Update tools and dependencies

### PR DESCRIPTION
**Pull request by nixpanic**
Update everything under `tools/` so that the latest versions are used. This requires updating the Go version, and re-generating some files.

### CODE REVIEW

**Comment by nixpanic** [comment]
As long as **Test building container images / build_bundle** fails, the problem obviously still exists. We'll nee to re-run the CI job on occasion to see if the issue has been resolved.

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@Mergifyio rebase

**Comment by nixpanic** [comment]
`make bundle` fails in the GitHub Workflow... but it works on my laptop, of course :disappointed:

**Review by yati1998 — APPROVED** [review]

**Review by riya-singhal31 — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergify queue

**Pull request merged**
