### PR TITLE
fix pvc reclaimspace & keyrotation annotation filter

### PR DESCRIPTION
**Pull request by iPraveenParihar**
This commit adds a check in StorageClass event handler to filter out PVC not needed for Reconcile.

- If the StorageClass has ReclaimSpace annotation,
   PVCs without ReclaimSpace annotations will be enqueued.
 - If the StorageClass has KeyRotation annotation,
    PVCs without the KeyRotation annotation will be enqueued.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@iPraveenParihar please add more details why not to requeue in this specific case which we are addressing here?

**Comment by iPraveenParihar** [comment]
> @iPraveenParihar please add more details why not to requeue in this specific case which we are addressing here?

Updated the PR description.

**Comment by Madhu-1** [comment]
> This commit adds a check in StorageClass event handler to filter out PVC not needed for Reconcile.
> 
> * If the StorageClass has ReclaimSpace annotation,
>   PVCs without ReclaimSpace annotations will be enqueued.
> * If the StorageClass has KeyRotation annotation,
>   PVCs without the KeyRotation annotation will be enqueued.

what will happen if i remove the annotation on the storageclass? i would expect that the annotations on the PVC's will be removed and reclaimspace/keyRotation CR's will get deleted, isn't that the case? have we documented what manual step user need to do in that case?

**Comment by Madhu-1** [comment]
> > This commit adds a check in StorageClass event handler to filter out PVC not needed for Reconcile.
> > 
> > * If the StorageClass has ReclaimSpace annotation,
> >   PVCs without ReclaimSpace annotations will be enqueued.
> > * If the StorageClass has KeyRotation annotation,
> >   PVCs without the KeyRotation annotation will be enqueued.
> 
> what will happen if i remove the annotation on the storageclass? i would expect that the annotations on the PVC's will be removed and reclaimspace/keyRotation CR's will get deleted, isn't that the case? have we documented what manual step user need to do in that case?

i see that its documented for now.

**Review by Rakshith-R — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
