### PR TITLE
set MaxConcurrentReconciles for VolumeReplication

### PR DESCRIPTION
**Pull request by Madhu-1**
Added option to set MaxConcurrentReconciles for VolumeReplication which was pending and for all other controllers this is set in #203

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
> Logger and replicationclient is shared in reconciler struct, this change will not be sufficient.
> 
Changed logger code replication client is not a problem it is initialized for each Reconcile.

> We need to implement something similar to networkfenceintance struct

**Comment by Rakshith-R** [comment]
> > Logger and replicationclient is shared in reconciler struct, this change will not be sufficient.
> 
> Changed logger code replication client is not a problem it is initialized for each Reconcile.
> 
> > We need to implement something similar to networkfenceintance struct

But it's set on the struct parameter here 😅
https://github.com/csi-addons/kubernetes-csi-addons/blob/2fc35bbb8a79fc97d2f64e2d9f0ec808c9982769/controllers/replication.storage/volumereplication_controller.go#L360

**Comment by Madhu-1** [comment]
> > > Logger and replicationclient is shared in reconciler struct, this change will not be sufficient.
> > 
> > 
> > Changed logger code replication client is not a problem it is initialized for each Reconcile.
> > > We need to implement something similar to networkfenceintance struct
> 
> But it's set on the struct parameter here sweat_smile
> 
> https://github.com/csi-addons/kubernetes-csi-addons/blob/2fc35bbb8a79fc97d2f64e2d9f0ec808c9982769/controllers/replication.storage/volumereplication_controller.go#L360

it will be set on every reconcile

**Comment by Rakshith-R** [comment]
> > > > Logger and replicationclient is shared in reconciler struct, this change will not be sufficient.
> > > 
> > > 
> > > Changed logger code replication client is not a problem it is initialized for each Reconcile.
> > > > We need to implement something similar to networkfenceintance struct
> > 
> > 
> > But it's set on the struct parameter here sweat_smile
> > https://github.com/csi-addons/kubernetes-csi-addons/blob/2fc35bbb8a79fc97d2f64e2d9f0ec808c9982769/controllers/replication.storage/volumereplication_controller.go#L360
> 
> it will be set on every reconcile

Yes, but now it'll be done parallely which will cause problem.

**Comment by Madhu-1** [comment]
> > > > > Logger and replicationclient is shared in reconciler struct, this change will not be sufficient.
> > > > 
> > > > 
> > > > Changed logger code replication client is not a problem it is initialized for each Reconcile.
> > > > > We need to implement something similar to networkfenceintance struct
> > > 
> > > 
> > > But it's set on the struct parameter here sweat_smile
> > > https://github.com/csi-addons/kubernetes-csi-addons/blob/2fc35bbb8a79fc97d2f64e2d9f0ec808c9982769/controllers/replication.storage/volumereplication_controller.go#L360
> > 
> > 
> > it will be set on every reconcile
> 
> Yes, but now it'll be done parallely which will cause problem.

AFAIK Each Reconcile request will get its own copy of the struct, and Even if we have multiple parallel request this should not an issue.

**Comment by Rakshith-R** [comment]
https://github.com/csi-addons/kubernetes-csi-addons/blob/2fc35bbb8a79fc97d2f64e2d9f0ec808c9982769/cmd/manager/main.go#L143

Negative, the same struct is used.

**Comment by Madhu-1** [comment]
> https://github.com/csi-addons/kubernetes-csi-addons/blob/2fc35bbb8a79fc97d2f64e2d9f0ec808c9982769/cmd/manager/main.go#L143
> 
> Negative, the same struct is used.

Not sure you are understanding what am trying to explain. Even the main struct is initialized here, and the controller framework will send this struct to all to reconcile with its own copy. Have you seen any issues with this change?

**Comment by Madhu-1** [comment]
I tested this one I dont see any problem with ReplicationClient, If you do see please let me know

**Review by Rakshith-R — APPROVED** [review]
:+1: , 
Lets take this in, 
I'll send a follow-up pr to add a replicationInstance struct to contain replication client and other required parameters for functions like https://github.com/csi-addons/kubernetes-csi-addons/blob/2fc35bbb8a79fc97d2f64e2d9f0ec808c9982769/controllers/replication.storage/volumereplication_controller.go#L446-L450

**Review by yati1998 — APPROVED** [review]

**Pull request merged**
